version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_USER=usuario123
      - DB_PASSWORD=DelfinesPacificos123
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=usersdb
    depends_on:
      - postgres
    command: ["sh", "-c", "sleep 10 && node server.js"]

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario123
      POSTGRES_PASSWORD: DelfinesPacificos123
      POSTGRES_DB: usersdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
